################################################################
### Configurations for forward/inverse implicitly padded     ###
### real-to-complex and complex-to-real 1D FFTs. These       ###
### will be used with the RealToComplexFFT1DGenerator class. ###
################################################################

# Forward: real-to-complex (R2C)
- signal_length:       64
  fft_size:            128  # 64 input + 64 zeros = 128 total
  input_data_type:     "float32"
  output_data_type:    "complex64"
  is_forward_fft:      true
  elements_per_thread: 8
  ffts_per_block:      2

- signal_length:       64
  fft_size:            256
  input_data_type:     "float32"
  output_data_type:    "complex64"
  is_forward_fft:      true
  elements_per_thread: 8
  ffts_per_block:      2

- signal_length:       64
  fft_size:            512
  input_data_type:     "float32"
  output_data_type:    "complex64"
  is_forward_fft:      true
  elements_per_thread: 8
  ffts_per_block:      2

- signal_length:       64
  fft_size:            1024
  input_data_type:     "float32"
  output_data_type:    "complex64"
  is_forward_fft:      true
  elements_per_thread: 8
  ffts_per_block:      2

- signal_length:       128
  fft_size:            256
  input_data_type:     "float32"
  output_data_type:    "complex64"
  is_forward_fft:      true
  elements_per_thread: 8
  ffts_per_block:      2

- signal_length:       128
  fft_size:            512
  input_data_type:     "float32"
  output_data_type:    "complex64"
  is_forward_fft:      true
  elements_per_thread: 8
  ffts_per_block:      2

- signal_length:       128
  fft_size:            1024
  input_data_type:     "float32"
  output_data_type:    "complex64"
  is_forward_fft:      true
  elements_per_thread: 8
  ffts_per_block:      2
  

# Inverse: complex-to-real (C2R)
